//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitodu.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AwaitingTrainingMailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AwaitingTrainingMailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitodu.Resource.AwaitingTrainingMailTemplate", typeof(AwaitingTrainingMailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -clientName-! &lt;br&gt;&lt;br&gt; Your workout starting at -date-, has just been accepted by your coach! Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; to take a look!.
        /// </summary>
        public static string AwaitingTrainingAcceptedClientBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingAcceptedClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new workout planned!.
        /// </summary>
        public static string AwaitingTrainingAcceptedClientSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingAcceptedClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -coachName-! &lt;br&gt;&lt;br&gt; Your workout with -clientName-, starting at -date-, has just been accepted by your client! Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; to take a look!.
        /// </summary>
        public static string AwaitingTrainingAcceptedCoachBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingAcceptedCoachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new workout planned!.
        /// </summary>
        public static string AwaitingTrainingAcceptedCoachSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingAcceptedCoachSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -clientName-! &lt;br&gt;&lt;br&gt; Your workout starting at -date-, has just been rejected by your coach. Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; to plan your workout at a different date!.
        /// </summary>
        public static string AwaitingTrainingRejectedClientBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingRejectedClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - your workout has been rejected.
        /// </summary>
        public static string AwaitingTrainingRejectedClientSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingRejectedClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -coachName-! &lt;br&gt;&lt;br&gt; Your workout with -clientName-, starting at -date-, has just been rejected by your client. Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; to plan your workout at a different date!.
        /// </summary>
        public static string AwaitingTrainingRejectedCoachBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingRejectedCoachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - your workout has been rejected.
        /// </summary>
        public static string AwaitingTrainingRejectedCoachSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingRejectedCoachSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -clientName-! &lt;br&gt;&lt;br&gt; Your workout awaiting your confirmation starting at -date-, has just been withdrawn by your coach. Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; if you want to suggest a new workout date to your coach!.
        /// </summary>
        public static string AwaitingTrainingWithdrawnClientBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingWithdrawnClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - one of your awaiting workouts had been withdrawn.
        /// </summary>
        public static string AwaitingTrainingWithdrawnClientSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingWithdrawnClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -coachName-! &lt;br&gt;&lt;br&gt; Workout with -clientName- awaiting your confirmation starting at -date-, has just been withdrawn by the client. Head to &lt;a href=&quot;-url-&quot;&gt;FITODU&lt;/a&gt; if you want to suggest a new workout date to your client!.
        /// </summary>
        public static string AwaitingTrainingWithdrawnCoachBody {
            get {
                return ResourceManager.GetString("AwaitingTrainingWithdrawnCoachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - one of your awaiting workouts had been withdrawn.
        /// </summary>
        public static string AwaitingTrainingWithdrawnCoachSubject {
            get {
                return ResourceManager.GetString("AwaitingTrainingWithdrawnCoachSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -fullName-!&lt;br&gt;&lt;br&gt;You have a new training request from -coachName-!&lt;br&gt;&lt;br&gt;To approve or reject it go to  our website: &lt;a href=&quot;-url-&quot;&gt;HERE&lt;/a&gt;. .
        /// </summary>
        public static string NewAwaitingTrainingClientBody {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new training request!.
        /// </summary>
        public static string NewAwaitingTrainingClientSubject {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -fullName-!&lt;br&gt;&lt;br&gt;You have a new training request from -clientName-!&lt;br&gt;&lt;br&gt;To approve or reject it go to  our website: &lt;a href=&quot;-url-&quot;&gt;HERE&lt;/a&gt;..
        /// </summary>
        public static string NewAwaitingTrainingCoachBody {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingCoachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new training request!.
        /// </summary>
        public static string NewAwaitingTrainingCoachSubject {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingCoachSubject", resourceCulture);
            }
        }
    }
}
