//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitodu.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AwaitingTrainingMailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AwaitingTrainingMailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitodu.Resource.AwaitingTrainingMailTemplate", typeof(AwaitingTrainingMailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -fullName-!&lt;br&gt;&lt;br&gt;You have a new training request from -coachName-!&lt;br&gt;&lt;br&gt;To approve or reject it go to  our website: &lt;a href=&quot;-url-&quot;&gt;HERE&lt;/a&gt;. .
        /// </summary>
        public static string NewAwaitingTrainingClientBody {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingClientBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new training request!.
        /// </summary>
        public static string NewAwaitingTrainingClientSubject {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingClientSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi -fullName-!&lt;br&gt;&lt;br&gt;You have a new training request from -clientName-!&lt;br&gt;&lt;br&gt;To approve or reject it go to  our website: &lt;a href=&quot;-url-&quot;&gt;HERE&lt;/a&gt;..
        /// </summary>
        public static string NewAwaitingTrainingCoachBody {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingCoachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitodu - you have a new training request!.
        /// </summary>
        public static string NewAwaitingTrainingCoachSubject {
            get {
                return ResourceManager.GetString("NewAwaitingTrainingCoachSubject", resourceCulture);
            }
        }
    }
}
