//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitodu.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitodu.Resource.ClientService", typeof(ClientService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add client to coach.
        /// </summary>
        public static string AddClientError {
            get {
                return ResourceManager.GetString("AddClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and coach are not connected.
        /// </summary>
        public static string ClientCoachError {
            get {
                return ResourceManager.GetString("ClientCoachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client doesn&apos;t exist.
        /// </summary>
        public static string ClientError {
            get {
                return ResourceManager.GetString("ClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found.
        /// </summary>
        public static string ClientNotFound {
            get {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update client register state.
        /// </summary>
        public static string ClientStateError {
            get {
                return ResourceManager.GetString("ClientStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach doesn&apos;t exist.
        /// </summary>
        public static string CoachError {
            get {
                return ResourceManager.GetString("CoachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coach not found.
        /// </summary>
        public static string CoachNotFound {
            get {
                return ResourceManager.GetString("CoachNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code expired.
        /// </summary>
        public static string CodeExpired {
            get {
                return ResourceManager.GetString("CodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create client.
        /// </summary>
        public static string CreateClientError {
            get {
                return ResourceManager.GetString("CreateClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create token.
        /// </summary>
        public static string CreateTokenError {
            get {
                return ResourceManager.GetString("CreateTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user.
        /// </summary>
        public static string CreateUserError {
            get {
                return ResourceManager.GetString("CreateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not a coach.
        /// </summary>
        public static string NotCoachError {
            get {
                return ResourceManager.GetString("NotCoachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client is not a dummy client.
        /// </summary>
        public static string NotDummyClientError {
            get {
                return ResourceManager.GetString("NotDummyClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get notes of another client.
        /// </summary>
        public static string NotesError {
            get {
                return ResourceManager.GetString("NotesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create private note.
        /// </summary>
        public static string PrivateNoteError {
            get {
                return ResourceManager.GetString("PrivateNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create public note.
        /// </summary>
        public static string PublicNoteError {
            get {
                return ResourceManager.GetString("PublicNoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting coach does not exist.
        /// </summary>
        public static string RequestingCoachError {
            get {
                return ResourceManager.GetString("RequestingCoachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting coach account role is not coach.
        /// </summary>
        public static string RequestingCoachRoleError {
            get {
                return ResourceManager.GetString("RequestingCoachRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save changes to the database.
        /// </summary>
        public static string SaveChangesError {
            get {
                return ResourceManager.GetString("SaveChangesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user is not a client of this coach.
        /// </summary>
        public static string SelectedClientError {
            get {
                return ResourceManager.GetString("SelectedClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not a client of selected coach.
        /// </summary>
        public static string SelectedCoachError {
            get {
                return ResourceManager.GetString("SelectedCoachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send email.
        /// </summary>
        public static string SendMailError {
            get {
                return ResourceManager.GetString("SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user (user already exists).
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add user to role.
        /// </summary>
        public static string UserRoleError {
            get {
                return ResourceManager.GetString("UserRoleError", resourceCulture);
            }
        }
    }
}
